version: "3.7"
services:
  app-server:
    image: cathaldonohoe/bebarter:latest
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: "mongodb://db"
    networks:
      - fyp
  app-client:
    image: cathaldonohoe/febarter:latest
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - app-server
    networks:
      - fyp
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: test
    volumes:
      - db-data:/data/db
    networks:
      - fyp
volumes:
  db-data:
networks:
  fyp: